name: mne-nirs
channels:
- conda-forge
dependencies:
- python>=3.8
- pip
- numpy
- scipy
- matplotlib
- numba
- pandas
- xlrd
- scikit-learn
- h5py
- h5io
- pillow
- statsmodels
- jupyter
- joblib
- psutil
- numexpr
- imageio
- tqdm
- spyder-kernels>=1.10.0
- imageio-ffmpeg>=0.4.1
- vtk>=9.0.1
- pyvista>=0.30
- pyvistaqt>=0.4
- qdarkstyle
- darkdetect
- dipy
- nibabel
- python-picard
- pyqt!=5.15.3
- mffpy>=0.5.7
- ipywidgets
- lxml
- pytables
- pooch
- nilearn
- mne>=0.24
- ipyvtklink
- mne-qt-browser
