name: Bot auto-merge
on: pull_request  # yamllint disable-line rule:truthy

jobs:
  autobot:
    permissions:
      contents: write
      pull-requests: write
      actions: write
    runs-on: ubuntu-latest
    if: (github.event.pull_request.user.login == 'dependabot[bot]' || github.event.pull_request.user.login == 'pre-commit-ci[bot]') && github.repository == 'mne-tools/mne-nirs'
    steps:
      - name: Enable auto-merge for bot PRs
        run: gh pr merge --auto --squash "$PR_URL" -A "50266005+mne-bot@users.noreply.github.com"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
